Dpl 177 cancel submission bug
sanger/sequencescape pull request #3440
Opened 2021-12-01 17:34 UTC by Sangeetha-Bheeman

Closes #

Changes proposed in this pull request:

*
*
* ...

2021-12-06 10:05 UTC, stevieing approved these changes

2021-12-06 11:30 UTC, sdjmchattie approved these changes

2021-12-06 11:39 UTC, emrojo requested changes

2021-12-06 11:39 UTC, emrojo commented on app/models/ability/administrator.rb
>    end
From reading the ticket content:
```
We should probably add can :cancel, Submission to both the lab_manager and sample_management_manager files...
```
I think to add this we would need to add the same change to app/models/ability/lab_manager and sample_management_manager

2021-12-07 15:24 UTC, sdjmchattie approved these changes

2021-12-08 09:59 UTC, emrojo approved these changes

2021-12-08 10:00 UTC, merged