DPL-900: add new RVI Cherrypick plate
sanger/sequencescape pull request #3904
Opened 2023-09-27 15:51 UTC by StephenHulme

Closes [DPL-900](https://github.com/sanger/sequencescape/issues/3897)

#### Changes proposed in this pull request

- add new RVI Cherrypick plate

#### Acceptance Criteria

- [x] RVI Cherrypick purpose definition created in Sequencescape and Limber
- [x] Plate purpose can be used in Sequencescape cherrypicking

#### Test Procedure

## RVI Cherry Picking Steps

1. Prepare Source Plates
   1. http://localhost:3000/uat_actions/generateplates
   1. Plate Purpose: RVI Cherrypick
   1. Well Count: 96
   1. Study: A study
   1. [Create Generate Plates]
   1. Copy plate barcode
1. Build a Submission
   1. http://localhost:3000/submissions/new
   1. Template: Cherrypick
   1. [Add Order]
   1. Study: A study
   1. Project name: A project
   1. From Plate and Wells
   1. {plate barcode>}
   1. [Save Order]
   1. [Build Submission]
1. Create Plate Template (once-off)
   1. http://localhost:3000/plate_templates/new?cols=12&rows=8
   1. Template name: Col12 Empty
1. Create a Batch
   1. http://localhost:3000/pipelines/16
   1. Select plates with {plate barcode}
   1. [Submit]
   1. [Select Plate Template]
   1. Output Plate Purpose: RVI Cherrypick
   1. Scan Partial Plate: {blank}
   1. Plate Template: Col12 Empty (optional)
   1. Control plate: RVI Viral RNA Phase 1 Control D1+ A1-
   1. Source plate type: Bio-Rad_96PCR
   1. Pick by µL
   1. 35µL
   1. [Next Step]
1. Approve Plate Layout
   1. (Should see a colourful plate layout)
   1. [Next step]
1. Finish Cherrypick
   1. [Release this batch]
   1. Take note of the output plate barcodes in the Output section
1. Check plate status in Limber
   1. http://localhost:3001
   1. Search for {output plate barcode}
   1. Status should be `Passed`
   1. Search for {original/input plate barcode}
   1. Status should be `Pending`
1. NOTE: the steps below do not result in the source plate being passed...
1. Pass the Plate
   1. http://localhost:3000/uat_actions/testsubmission
   1. Submission Template: Cherrypick
   1. Plate barcode: {input plate barcode}
   1. Number of wells with samples: {blank}
   1. Number of wells to submit: {blank}
   1. [Create Test Submission]
1. Refresh plate page in Limber - Status should now be `Passed`

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2023-10-09 08:11 UTC, andrewsparkes requested changes

2023-10-09 08:11 UTC, andrewsparkes commented on config/default_records/plate_purposes/005_limber_purposes.yml
> +  <<: *limber_input_96
You've set it as an input plate here, but input false in Limber.
Needs to be consistent

2023-10-10 14:33 UTC, andrewsparkes approved these changes

2023-10-10 14:33 UTC, emrojo approved these changes

2023-11-06 09:37 UTC, merged