Bugfix mbrave receive
sanger/sequencescape pull request #3991
Opened 2023-12-15 15:30 UTC by emrojo

Closes #

#### Changes proposed in this pull request

- 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2023-12-15 16:02 UTC, andrewsparkes requested changes

2023-12-15 16:02 UTC, andrewsparkes commented on lib/tasks/insdc/import_countries.rake
> +}.freeze unless defined?(INSDC_COUNTRIES_DEFAULTS)
what are these about?

2023-12-18 09:35 UTC, emrojo commented on lib/tasks/insdc/import_countries.rake
> +}.freeze unless defined?(INSDC_COUNTRIES_DEFAULTS)
They were warnings displayed when running rake tasks

2024-08-21 08:03 UTC, stevieing commented
closed as stale.

2024-08-21 08:03 UTC, closed without merging