Fix: Add uuid to tube purpose resource
sanger/sequencescape pull request #4230
Opened 2024-07-25 13:02 UTC by KatyTaylor

- it was breaking Limber config generate task as that needed to retrieve the uuid
- copied over from the plate purpose resource

Closes #

#### Changes proposed in this pull request

- 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2024-07-25 13:30 UTC, sdjmchattie requested changes
I think we need to update the tests to make sure this cannot be set during creation or updated.  I think we also need to `default_includes :uuid` near the top of the resource.

2024-07-25 13:30 UTC, sdjmchattie commented on app/resources/api/v2/tube_purpose_resource.rb
> +      # @return [String] gets the UUID of the tube purpose.
```suggestion
      # @return [String] The UUID of the tube purpose.
```

2024-07-25 13:30 UTC, andrewsparkes approved these changes

2024-07-25 13:31 UTC, KatyTaylor commented
> I think we need to update the tests to make sure this cannot be set during creation or updated. I think we also need to `default_includes :uuid` near the top of the resource.

okidoke

2024-07-26 08:49 UTC, sdjmchattie approved these changes

2024-07-26 08:54 UTC, andrewsparkes commented on spec/requests/api/v2/tube_purposes_spec.rb
> +        expect(response).to have_http_status(400)
just fix these 400s as github suggests I think

2024-07-26 09:42 UTC, merged