4409 y24 379  study setup fields to align to the ena database fields
sanger/sequencescape pull request #4542
Opened 2024-12-03 14:48 UTC by wendyyang

Closes #

#### Changes proposed in this pull request
add ENA database fields
add to the study setup page

- 

#### Instructions for Reviewers

_[All PRs] - Confirm PR template filled_  
_[Feature Branches] - Review code_  
_[Production Merges to `main`]_  
 &nbsp; &nbsp; \- _Check story numbers included_  
 &nbsp; &nbsp; \- _Check for debug code_  
 &nbsp; &nbsp; \- _Check version_

2025-01-06 14:44 UTC, BenTopping requested changes
Good start, couple suggestions about data validation and creation.

2025-01-06 14:44 UTC, BenTopping commented on .rubocop_todo.yml
> +    - 'config/initializers/ena_requirement_fields.rb'
Not sure this is needed as we don't want to add rubocop exceptions if we don't have to. Did you try fixing the failing rubocop errors?

2025-01-06 14:44 UTC, BenTopping commented on app/models/study.rb
> +    validates :ebi_library_strategy, inclusion: { in: EBI_LIBRARY_STRATEGY_OPTIONS }
Can these be nil or are these required for all studies? Do we need to add a conditional to these so they are just checked for ENA studies?

2025-01-06 14:44 UTC, BenTopping commented on app/uat_actions/uat_actions/generate_study.rb
> +        ebi_library_strategy: 'WGS',
Do these need to be here, are they mandatory for all studies?

2025-01-06 14:44 UTC, BenTopping commented on app/views/shared/metadata/show/_study.html.erb
> +    <%= metadata_fields.plain_value(:ebi_library_strategy) %>
Should these be part of the above ENA requirement group?

2025-01-06 14:44 UTC, BenTopping commented on db/migrate/20241126115246_add_ebi_library_strategy_to_studay_metadata.rb
These three migrations can be combined into one.

2025-01-06 14:44 UTC, BenTopping commented on app/api/io/study.rb
> +study_metadata.contaminated_human_data_access_group => contaminated_human_data_access_group
Do they need to be added here? This is the old API not sure if its needed.

2025-01-06 14:52 UTC, wendyyang commented on .rubocop_todo.yml
> +    - 'config/initializers/ena_requirement_fields.rb'
Not yet.

2025-01-07 09:54 UTC, stevieing commented on app/api/io/study.rb
> +study_metadata.contaminated_human_data_access_group => contaminated_human_data_access_group
API V1 is no longer used.

2025-01-07 09:55 UTC, stevieing commented on config/ENA_requirement_fields.yml
> +EBI_Library_strategy:
The name of this file is ENA_requirement_fields and the initializer is looking for ena_requirement_fields.

CI is case sensitive.

2025-01-07 09:57 UTC, stevieing commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
It is looking for ena_requirement_fields but the file name is ENA_requirement_fields.

It is probably better to use config_for rather than an initializer.

2025-01-07 09:58 UTC, stevieing commented on app/models/study.rb
> +  EBI_LIBRARY_STRATEGY_OPTIONS = EBI_REQUIREMENT_FIELDS['EBI_Library_strategy']
If you use config_for then you can use the options directly in study without having to redefine them.

2025-01-07 09:59 UTC, wendyyang commented on config/ENA_requirement_fields.yml
> +EBI_Library_strategy:
Thank you very much for spotting this. I didn't notice that all of the files in config/initialser are lower cases.

2025-01-08 09:16 UTC, wendyyang commented on .rubocop_todo.yml
> +    - 'config/initializers/ena_requirement_fields.rb'
removed

2025-01-08 09:18 UTC, wendyyang commented on app/api/io/study.rb
> +study_metadata.contaminated_human_data_access_group => contaminated_human_data_access_group
removed

2025-01-08 19:14 UTC, wendyyang commented on db/migrate/20241126115246_add_ebi_library_strategy_to_studay_metadata.rb
combined

2025-01-14 14:47 UTC, wendyyang commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
@stevieing I have made the changes for config_for, but not working. errors are:
/Users/wy1/Documents/workspace/sequencescape/app/models/study.rb:93:in `<class:Study>': undefined method `[]' for nil:NilClass (NoMethodError)

  EBI_LIBRARY_STRATEGY_OPTIONS = Rails.configuration.ena_requirement_fields["EBI_Library_strategy"]
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^

It seems not able to load the configuration correctly, anything missing here?

2025-01-14 14:55 UTC, stevieing commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
I will have a look.

2025-01-14 15:14 UTC, stevieing commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
@wendyyang I have resolved it.

2025-01-14 15:15 UTC, wendyyang commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
when was the problem?

2025-01-14 15:20 UTC, stevieing commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
The yml file needs to be in the top level of the config directory otherwise Rails can't find it.

2025-01-14 15:25 UTC, wendyyang commented on config/initializers/ena_requirement_fields.rb
> +file_path = Rails.root.join('config/ena_requirement_fields.yml')
I see. Thank you very much!

2025-01-14 15:52 UTC, stevieing commented on config/initializers/ena_requirement_fields.rb
> +# frozen_string_literal: true
you can remove this file now?

2025-01-14 15:53 UTC, wendyyang commented on config/initializers/ena_requirement_fields.rb
> +# frozen_string_literal: true
yes. will do.

2025-01-15 11:21 UTC, stevieing requested changes
The new code is working fine now.

It is failing CI though and there is a merge conflict so it might be worth merging develop or rebasing.

2025-01-21 09:59 UTC, stevieing approved these changes

2025-01-21 10:00 UTC, stevieing reviewed
I think you will need to merge develop and resolve the conflicts.

2025-01-21 10:38 UTC, merged